version: "3.8"

services:
    proxy:
        image: nginx:latest
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - server
        ports:
            - target: 3000
              published: 3030
              mode: host
        networks:
            - backend

    server:
        image: pxseu/pxseu-dot-com_web:latest
        build:
            context: .
            dockerfile: ./packages/web/Dockerfile
        environment:
            - NEXT_PUBLIC_API_ROUTE=http://localhost:3000
        ports:
            - target: 80
        networks:
            - backend
        deploy:
            replicas: 4
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
                delay: 20s
            rollback_config:
                parallelism: 0
                order: stop-first
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
        healthcheck:
            test: curl --fail http://localhost/ || exit 1
            interval: 10s
            retries: 5
            start_period: 5s
            timeout: 10s

networks:
    backend:
        name: pxseu_web_swarm
        driver: overlay
