version: "3.9"
services:
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
    api:
        container_name: api
        build:
            context: .
            dockerfile: ./packages/api/Dockerfile
        ports:
            - "8080:80"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
