version: "3.8"

services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    nginx:
        image: nginx:latest
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api
        ports:
            - "3000:3000"

    api:
        build:
            context: .
            dockerfile: ./packages/api/Dockerfile
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
