version: "3.8"

services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - backend

    nginx:
        image: nginx:latest
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api
        ports:
            - target: 3000
              published: 3000
              protocol: tcp
              mode: host
        networks:
            - backend
        deploy:
            placement:
                constraints: [node.role == manager]
    api:
        image: pxseu/pxseu-dot-com_api
        build:
            context: .
            dockerfile: ./packages/api/Dockerfile
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        # env_file: ./packages/api/.env.local
        depends_on:
            - redis
        networks:
            - backend
        ports:
            - 80:80
        deploy:
            replicas: 4
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
                delay: 10s
            rollback_config:
                parallelism: 0
                order: stop-first
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/health || exit 1"]

networks:
    backend:
        name: pxseu_api_swarm
