version: "3.9"

services:
    redis:
        # container_name: pxseu-dot-com_redis
        image: redis:latest
        ports:
            - "6379:6379"

    nginx:
        # container_name: pxseu-dot-com_nginx
        image: nginx:latest
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api
        ports:
            - "5050:5050"

    api:
        # container_name: pxseu-dot-com_api
        build:
            context: .
            dockerfile: ./packages/api/Dockerfile
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
