version: "3.9"

services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    nginx:
        image: nginx:latest
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api
            - web
        ports:
            - "3050:5050"
            - "3060:5060"

    api:
        build:
            context: .
            dockerfile: ./packages/api/Dockerfile
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis

    web:
        build:
            context: .
            dockerfile: ./packages/web/Dockerfile
        depends_on:
            - api
