version: "3.8"

services:
    redis:
        image: redis:latest
        ports:
            - target: 6379
        networks:
            - backend

    nginx:
        image: nginx:latest
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api
        ports:
            - target: 3000
              published: 3000
              mode: host
        networks:
            - backend
    api:
        image: pxseu/pxseu-dot-com_api
        build:
            context: .
            dockerfile: ./packages/api/Dockerfile
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - target: 80
        depends_on:
            - redis
        networks:
            - backend
        deploy:
            replicas: 4
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
                delay: 10s
            rollback_config:
                parallelism: 0
                order: stop-first
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
        # healthcheck:
        #     test: ["CMD", "curl -f http://localhost/health || exit 1"]

networks:
    backend:
        name: pxseu_api_swarm
        driver: overlay
