name: CI Deploy

on:
    workflow_run:
        workflows: ["CI Build"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy api on the VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd ~/deploy/monorepo
                      git reset --hard
                      git pull
                      docker service update --image pxseu/pxseu-dot-com_api pxseu-dot-com_zero_api
